---
title: "Sensitivity"
author: "BBL"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

# Load packages
library(PoolDilutionR)
library(dplyr)
library(ggplot2)
library(ggpmisc)
library(ggh4x)
library(lubridate)
library(readr)
library(scales)
library(tibble)
library(tidyr)
library(kableExtra)

theme_set(theme_minimal() + theme(text = element_text(size = 11)))

if(!file.exists("outputs/incdat.csv")) {
  stop("You need to run the main RMarkdown file first")
}
incdat <- read_csv("outputs/incdat.csv")
```

# Model-fitting sensitivity

```{r Set Constants, echo=FALSE}
FRAC_K <- 0.98 # 13C consumption as a fraction of 12C consumption (alpha in Eq. 11)
FRAC_P <- 0.01 # 13C production as a fraction of 12C production
AP_P <- FRAC_P / (1 + FRAC_P) * 100 # 13C atom percent of total methane production
VOL_ML <- 130  # total volume of jar
```




```{r Do the thing!, include=FALSE}
fit_models <- function(incdat) {
  pk_results <- list()
  
  for(i in unique(incdat$id)) {
    # Isolate this sample's data
    incdat %>%
      filter(id == i) %>%
      select(id, round, vol, time_days,
             cal12CH4ml, cal13CH4ml,
             AP_obs, Nm, Nd) ->
      dat
    
    # Let optim() try different values for P and k until it finds best fit to data
    params <- list("P0" = 10) # k0 is auto-estimated
    result <- optimize_pk(time = dat$time_days,
                          m = dat$cal12CH4ml + dat$cal13CH4ml,
                          n = dat$cal13CH4ml,
                          Nm = dat$Nm,
                          Nd = dat$Nd,
                          params = params)
    
    P <- result$par["P"]
    pk_results[[i]] <- tibble(id = i,
                              P = P,
                              k = result$par["k"],
                              k0 = result$initial_par["k0"],
                              value = result$value,
                              convergence = result$convergence,
                              message = result$message)
  }
  bind_rows(pk_results)
}

```

## How sensitive are we to removing first/last data points?

```{r, include=FALSE, eval=FALSE}
results <- fit_models(incdat)
results$which <- "Default"

incdat %>% 
  group_by(id) %>% 
  slice_tail(n = -1) %>% 
  mutate(time_days = time_days - min(time_days)) %>% 
  fit_models() ->
  results_drop_first
results_drop_first$which <- "Drop first"

incdat %>% 
  group_by(id) %>% 
  slice_head(n = -1) %>% 
  fit_models() ->
  results_drop_last
results_drop_last$which <- "Drop last"
```


```{r, echo=FALSE}
bind_rows(results_drop_first, results_drop_last) %>% 
  left_join(select(results, id, P_default = P, k_default = k), by = "id") %>% 
  mutate(P_change = 100 * (P - P_default) / P, 
         k_change = 100 * (k - k_default) / k) ->
  results_all

results_all %>% 
  pivot_longer(cols = c("P_change", "k_change")) %>% 
  ggplot(aes(value, id, color = name)) + 
  geom_point() + xlab("Change (%)") + 
  facet_wrap(~which)

results_all %>% 
  filter(!is.infinite(P_change)) %>% 
  group_by(which) %>% 
  summarise(P_change_percent = round(median(P_change, na.rm = TRUE), 1),
            k_change_percent = round(median(k_change, na.rm = TRUE), 1)) %>% 
  knitr::kable()
```


## How sensitive are results to FRAC_P and FRAC_K?

```{r, include=FALSE}
FRAC_K_original <- FRAC_K
FRAC_P_original <- FRAC_P

N <- 10
set.seed(27)
# This is crude but produces a lognormal distribution with a max
# of ~0.999 and a minimum of 0.916
#frac_k_values <- FRAC_K - (rlnorm(N) / 100 - 0.02)
frac_k_values <- seq(0.9, 0.999, length.out = N)
# Lognormal again, min = 0.0005, max = 0.064
#frac_p_values <- FRAC_P + (rlnorm(N) / 100 - 0.01)
frac_p_values <- seq(0.001, 0.1, length.out = N)

out <- list()
time_start <- Sys.time()
for(i in c("2", "31", "52", "61", "64", "71")) {
  incdat %>% filter(id == i) -> incdat_i
  for(fk in frac_k_values) {
    for(fp in frac_p_values) {
      FRAC_K <- fk
      FRAC_P <- fp
      incdat_i %>% 
        fit_models() %>% 
        mutate(`Initial frac_p` = fp, `Initial frac_k` = fk) ->
        out[[paste(i, fk, fp)]]
    }
  }  
}
print(difftime(Sys.time(), time_start))

frac_pk_results <- bind_rows(out)

ggplot(subset(frac_pk_results), aes(`Initial frac_p`, `Initial frac_k`)) +
  facet_wrap(~id) + 
  geom_tile(aes(fill = value)) + 
  scale_fill_gradientn("Cost (fit)", trans = "log", colours = terrain.colors(5))
```



# Reproducibility

```{r, echo=FALSE}
sessionInfo()
```

